project_id = "iwpqorlvzxudvpjrbqqz"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323
api_url = "http://127.0.0.1:54321"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[functions.create-esewa-payment]
verify_jwt = true

[functions.verify-esewa-payment]
verify_jwt = false